name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8.2]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install pandas
        python -m pip install numpy
        python -m pip install datetime
        python -m pip install opencensus-ext-azure
        python -m pip install requests
    - name: Bot Test with pytest
      env:
        INSIGHTS_CONNECTION_STRING: ${{ secrets.INSIGHTS_CONNECTION_STRING }}
        LUIS_APP_ID: ${{ secrets.LUIS_APP_ID }}
        PRED_ENDPOINT: ${{ secrets.PRED_ENDPOINT }}
        PRED_KEY: ${{ secrets.PRED_KEY }}
      run: |
        pytest